modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="igauntlet"
version="${file.jarVersion}"
displayName="IGauntlet Mod"
updateJSONURL="https://minecraft.curseforge.com/projects/igauntlet" #optional
displayURL="https://discord.gg/pQkRKKN" #optional
logoFile="gauntlet.png" #optional
credits="JMTeam"
authors="Josia50, rootheworld, UKMinecrafted, Ben1Ben1"
description='''
Control Reality, Space, Power, Time and Mind!
'''
[[dependencies.igauntlet]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.igauntlet]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
